name: CI

on:
  push:
    paths-ignore:
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'


  workflow_dispatch:
  
jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Runn unitests
        run: ./gradlew lintDebug testDebugUnitTest --stacktrace -DskipFormatKtlint

      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: report.html
          path: app/build/reports/lint-results-debug.html
