name: Android build app

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'

  workflow_dispatch:
  
jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Debug APK
        run: ./gradlew assembleDebug lintDebug testDebugUnitTest --stacktrace -DskipFormatKtlint

      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: app/build/reports/lint-results-debug.html
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
