# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android build app

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Debug APK
        run: ./gradlew assembleDebug --stacktrace
        
#       - name: Generate Release APK
#         run: ./gradlew assembleRelease --stacktrace
        
      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          
      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

